### ISSUE TITLE
rename repo from hbdet to AcoDet

### ISSUE THREAD

**Issue by vskode** [vskode/acodet#11]
error is thrown by model, because hbdet is saved in model lambda layer

**Comment by vskode** [comment]
AcoDet is not conform with PEP 8. While at it might make sense to rename to acodet.

**Comment by vskode** [comment]
- [ ] redo readme file

**Comment by vskode** [comment]
- [ ] save model again to get rid of lambda layer warning regarding hbdet

**Comment by davidm2894** [comment]
hbdnet's dead

**Comment by vskode** [comment]
model lambda layers changed from hbdet to acodet. Models were tested.
