### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by miguelblazquezhervas** [vskode/acodet#27]
Hi Vincent,

I cannot run the program using the **streamlit run streamlit_run.app** command and I got this error message: "_Streamlit requires raw Python (.py) files, not .app_."

Installation seemed to work well, but after checking the Scripts folder in the env_acodet environment, I see that streamlit is actually an application and not an .py file as would be required.

Do you know how could I solve this issue?

Many thanks!

Miguel.

**Comment by vskode** [comment]
Hi Miguel,

thanks for reaching out to me. I apologize, I misspelled the command, it should be `streamlit run streamlit_app.py`. Try running that and let me know if it works.

I'll make sure to fix that error in the Readme file. 

Best,
Vincent

**Comment by miguelblazquezhervas** [comment]
Hi Vincent,

Thanks for replying so quickly! I managed to change the code to run streamlit. However, I got the following error in my browser:

ModuleNotFoundError: No module named 'yaml'
Traceback:

File "C:\Users\Usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
File "C:\Users\Usuario\acodet\streamlit_app.py", line 2, in <module>
    from acodet.create_session_file import create_session_file, read_session_file
File "acodet\acodet\create_session_file.py", line 1, in <module>
    import yaml

I am not a proficient python user. Any idea of what this means?

Thanks!

**Comment by vskode** [comment]
Hi Miguel,
the error you are getting indicates, that you don't the module yaml installed. I am not able to reproduce your error. Could it maybe be that you haven't activated your virtual environment? You're virtual environment is necessary to load the necessary modules. To activate the environment run the command `source ../env_acodet/bin/activate` (Mac/Linux) `source ../env_acodet/Scripts/activate` (Windows). make sure that you have installed the virtual environment according to the installation instructions and that you are in the directory acodet.
Hope this helps.
Best,
Vincent

**Comment by miguelblazquezhervas** [comment]
Hi Vincent,

I finally managed to run the program properly. I had to reinstall everything but it seemed that the issue was all about where all the files were initially allocated in my system. That's why the commands I was using were not working and why you could not reproduce the errors.

Now, I'll see how it goes, but hopefully will be fine.

Many thanks for following up!

Miguel.
